-- Content Planner Schema (V3.0.0)

-- 1. Planning Cycles
-- Stores the high-level strategy (30/60/90 days)
CREATE TABLE IF NOT EXISTS planning_cycles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID, -- Nullable for local dev (No Auth)
    name TEXT NOT NULL, -- e.g., "Q1 2026 Strategy"
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    duration_days INTEGER NOT NULL CHECK (duration_days IN (30, 60, 90)),
    thesis TEXT, -- The central strategic thesis
    schedule_days TEXT[], -- Array of days e.g. ['Mon', 'Wed', 'Fri']
    status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'active', 'completed')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Planning Pillars
-- Defines the thematic pillars for a cycle
CREATE TABLE IF NOT EXISTS planning_pillars (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    cycle_id UUID NOT NULL REFERENCES planning_cycles(id) ON DELETE CASCADE,
    name TEXT NOT NULL, -- e.g., "IA como Sistema de Decisão"
    key_message TEXT, -- "IA não é ferramenta..."
    focus_area TEXT, -- "Conectar IA a impacto..."
    proportion INTEGER DEFAULT 0, -- Percentage 0-100
    color TEXT DEFAULT '#cbd5e1', -- Hex code for UI
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Planned Posts
-- The actual content schedule generated by AI
CREATE TABLE IF NOT EXISTS planned_posts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    cycle_id UUID NOT NULL REFERENCES planning_cycles(id) ON DELETE CASCADE,
    pillar_id UUID REFERENCES planning_pillars(id) ON DELETE SET NULL,
    date DATE NOT NULL, -- Scheduled date
    theme TEXT NOT NULL, -- The specific topic
    title TEXT, -- Draft title
    format TEXT, -- Framework, Provocação, Storytelling, etc.
    objective TEXT, -- Autoridade técnica, Debate executivo, etc.
    perspective TEXT, -- The specific angle/hook
    content_draft TEXT, -- Full content
    status TEXT DEFAULT 'planned' CHECK (status IN ('planned', 'drafted', 'published')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- DEV MODE: DISABLE RLS (Matches current 'No Auth' setup)
ALTER TABLE planning_cycles DISABLE ROW LEVEL SECURITY;
ALTER TABLE planning_pillars DISABLE ROW LEVEL SECURITY;
ALTER TABLE planned_posts DISABLE ROW LEVEL SECURITY;

-- If we were using RLS, we would add policies here.
-- For now, we trust the app to manage access.
